version: '3.4'

services:
  quizzapp:
    container_name: quizzapp
    image: quizmasterapi
    build:
      context: .
      dockerfile: QuizMaster.API/Dockerfile
    depends_on:
      - sql_server_identity
    ports:
      - 8080:80 
    environment:
      - CONNECTIONSTRINGS__QUIZMASTERCONNECTION=Server=sql_server_identity;Database=QuizzDatabase;User=sa;Password=Nathan_musoko123;Encrypt=false;
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - quiz_network

  sql_server_identity:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=Nathan_musoko123
      - ACCEPT_EULA=Y
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql
    networks:
      - quiz_network
  front:
     image: front
     build:
       context: ../QuizAppFront/front
       dockerfile: ./Dockerfile
     environment:
       NODE_ENV: production
     ports:
       - 3000:3000
     depends_on:
      - quizzapp
     networks:
      - quiz_network

volumes:
  data:


networks:
  quiz_network: 
    driver: bridge  